### ISSUE TITLE
11.0.1  20b50版本无法引导成功

### ISSUE THREAD

**Issue by asdqian** [Cluas/MSI-b450m-OC#1]

**Comment by Cluas** [comment]
> _No description provided._

具体报啥错 我这边正常

**Comment by asdqian** [comment]
在 virtualsmc  efend  那卡住了，一直不动。 不开跑码模式就是闪一下苹果标志，直接重启了。 我的配置是：R5 2600 +B450火箭筒+rx590

**Comment by asdqian** [comment]
引导卡住的照片发到你邮箱了

**Comment by Cluas** [comment]
> 在 virtualsmc  efend  那卡住了，一直不动。 不开跑码模式就是闪一下苹果标志，直接重启了。 我的配置是：R5 2600 +B450火箭筒+rx590

我按照错误日志搜下方案吧 硬件不同我也不能确定是啥问题

**Comment by asdqian** [comment]
嗯嗯 多谢。打错了B450M火箭筒。  和B450M迫击炮应该差别不大
