### ISSUE TITLE
SSDT-RX Vega 56.aml 

### ISSUE THREAD

**Issue by sighzh** [Cluas/MSI-b450m-OC#2]
这文件是针对vega56的吧

**Comment by sighzh** [comment]
除显卡是5700外，其他一致，除了改3码，我还需要改什么，开机到苹果图标闪一下就重启了

**Comment by Cluas** [comment]
> 除显卡是5700外，其他一致，除了改3码，我还需要改什么，开机到苹果图标闪一下就重启了

把这个文件去掉 重新加载下配置 然后去https://opencore.slowgeek.com/检测下配置，然后BIOS里面配置一下 重启的话有可能是BIOS配置问题 改成UEFI启动

**Comment by sighzh** [comment]
我一直是UEFI启动的，换了份efi文件就好了，我的mac机型不能是imacpro1,1 得改成macpro7,1，否则就黑屏，现在就是一直提示内存问题和声卡老是有电流声，还有虚拟机用不了

**Comment by Cluas** [comment]
> 我一直是UEFI启动的，换了份efi文件就好了，我的mac机型不能是imacpro1,1 得改成macpro7,1，否则就黑屏，现在就是一直提示内存问题和声卡老是有电流声，还有虚拟机用不了

虚拟机要在bios里设置下

**Comment by sighzh** [comment]
设置过，只能无界面启动
