### ISSUE TITLE
微星B450M GAMING PLUS可以使用您EFI吗？

### ISSUE THREAD

**Issue by wqianglxf** [Cluas/MSI-b450m-OC#3]
AMD Ryzen 2700

MSI B450M GAMING PLUS

蓝宝石 5700

网卡T919

**Comment by Cluas** [comment]
> AMD Ryzen 2700
> 
> MSI B450M GAMING PLUS
> 
> 蓝宝石 5700
> 
> 网卡T919

不保证兼容性 推荐按照reademe里的链接自己一步步配置吧
